   1 - """                                                                                                                                                                                                                                      │    
│   2 - 하나투어 여행 상품 성과 및 전략 분석 대시보드 (최종 전략 구조 100% 반영 완본)                                                                                                                                                            │    
│   3 -                                                                                                                                                                                                                                          │    
│   4 - 본 파일은 doc/structure_modified.md에서 정의된 5단계 분석 프레임워크를 기반으로 구성되었습니다.                                                                                                                                          │    
│   5 - 초보 분석가를 위해 각 시각화의 통계적 의미와 비즈니스 해석 관점을 상세히 주석으로 설명합니다.                                                                                                                                            │    
│   6 -                                                                                                                                                                                                                                          │    
│   7 - 주요 분석 단계:                                                                                                                                                                                                                          │    
│   8 - 1. 📈 시장 거시 분석: 글로벌 항공 수요 및 노선별 점유율                                                                                                                                                                                  │    
│   9 - 2. 📦 상품 포트폴리오: 쇼핑-가격 상관관계 및 다낭 수익 모델 진단                                                                                                                                                                         │    
│  10 - 3. ⭐ 만족도 상관관계: 편중도, 중요도, 데드크로스 분석                                                                                                                                                                                   │    
│  11 - 4. 🧠 Deep Insight: AI 기반 부정 원인 분류 및 페르소나별 감성 분석                                                                                                                                                                       │    
│  12 - 5. 🛡️ 리스크 및 전략: LTV 매트릭스, ROI 시뮬레이션 및 고위험 관리                                                                                                                                                                        │    
│  13 - """                                                                                                                                                                                                                                      │    
│  14 -                                                                                                                                                                                                                                          │    
│  15 - import streamlit as st # 웹 대시보드 제작 프레임워크                                                                                                                                                                                     │    
│  16 - import pandas as pd # 데이터 프레임 처리                                                                                                                                                                                                 │    
│  17 - import plotly.express as px # 인터랙티브 시각화 (산점도, 히스토그램 등)                                                                                                                                                                  │    
│  18 - import plotly.graph_objects as go # 정밀 차트 및 이중 축(Dual-Axis) 구현                                                                                                                                                                 │    
│  19 - from plotly.subplots import make_subplots # 서브플롯 생성 도구                                                                                                                                                                           │    
│  20 - from src.analytics_engine import AnalyticsEngine # 분석 로직을 담당하는 핵심 엔진                                                                                                                                                        │    
│  21 - from src.ui_elements import render_analysis_box, apply_custom_style # 커스텀 UI 구성 요소                                                                                                                                                │    
│  22 -                                                                                                                                                                                                                                          │    
│  23 - # ---------------------------------------------------------                                                                                                                                                                              │    
│  24 - # 1. 전역 설정 및 분석 엔진 초기화                                                                                                                                                                                                       │    
│  25 - # ---------------------------------------------------------                                                                                                                                                                              │    
│  26 - # 페이지 레이아웃을 'wide'로 설정하여 넓은 화면 활용                                                                                                                                                                                     │    
│  27 - st.set_page_config(page_title="HanaTour Strategy Dashboard", layout="wide")                                                                                                                                                              │    
│  28 - # 하나투어 브랜드 가이드라인에 맞춘 스타일 적용                                                                                                                                                                                          │    
│  29 - apply_custom_style()                                                                                                                                                                                                                     │    
│  30 -                                                                                                                                                                                                                                          │    
│  31 - @st.cache_resource # 리소스 로딩 속도 향상을 위해 엔진 인스턴스 캐싱                                                                                                                                                                     │    
│  32 - def get_engine():                                                                                                                                                                                                                        │    
│  33 -     """분석 엔진인 AnalyticsEngine의 인스턴스를 생성하고 유지합니다."""                                                                                                                                                                  │    
│  34 -     return AnalyticsEngine()                                                                                                                                                                                                             │    
│  35 -                                                                                                                                                                                                                                          │    
│  36 - engine = get_engine()                                                                                                                                                                                                                    │    
│  37 - df = engine.df # 전체 데이터셋 로드                                                                                                                                                                                                      │    
│  38 -                                                                                                                                                                                                                                          │    
│  39 - # ---------------------------------------------------------                                                                                                                                                                              │    
│  40 - # 2. 사이드바 메뉴 및 전역 필터 구성                                                                                                                                                                                                     │    
│  41 - # ---------------------------------------------------------                                                                                                                                                                              │    
│  43 - st.sidebar.title("📋 전략 분석 프레임워크")                                                                                                                                                                                              │    
│  44 -                                                                                                                                                                                                                                          │    
│  45 - # doc/structure_modified.md에 정의된 5개 대메뉴 구성                                                                                                                                                                                     │    
│  46 - menu_options = [                                                                                                                                                                                                                         │    
│  47 -     "📈 1. 시장 거시 분석 (Market)",                                                                                                                                                                                                     │    
│  48 -     "📦 2. 상품 포트폴리오 (Mix)",                                                                                                                                                                                                       │    
│  49 -     "⭐ 3. 만족도 상관관계 (Value)",                                                                                                                                                                                                     │    
│  50 -     "🧠 4. AI Deep Insight (Voice)",                                                                                                                                                                                                     │    
│  51 -     "🛡️ 5. 리스크 및 KPI (Strategy)"                                                                                                                                                                                                     │    
│  52 - ]                                                                                                                                                                                                                                        │    
│  53 - selected_menu = st.sidebar.radio("분석 단계를 선택하세요", menu_options)                                                                                                                                                                 │    
│  54 -                                                                                                                                                                                                                                          │    
│  55 - # 전역 필터: 분석 대상 도시를 사용자가 직접 선택 (기본값: 전체)                                                                                                                                                                          │    
│  56 - target_cities = st.sidebar.multiselect("📍 분석 타겟 도시", ["다낭", "나트랑", "싱가포르"], default=["다낭", "나트랑", "싱가포르"])                                                                                                      │    
│  57 - filtered_df = df[df['대상도시'].isin(target_cities)]                                                                                                                                                                                     │    
│  58 -                                                                                                                                                                                                                                          │    
│  59 - # ---------------------------------------------------------                                                                                                                                                                              │    
│  60 - # 3. 상단 핵심 KPI (실시간 비즈니스 현황)                                                                                                                                                                                                │    
│  61 - # ---------------------------------------------------------                                                                                                                                                                              │    
│  62 - st.title("✈️ 하나투어 데이터 전략 의사결정 시스템")                                                                                                                                                                                      │    
│  63 - st.markdown("---")                                                                                                                                                                                                                       │    
│  64 -                                                                                                                                                                                                                                          │    
│  65 - # 보고서 팁 반영: 최상단에 5번 섹션의 핵심 KPI를 노출하여 즉각적 상황 파악 지원                                                                                                                                                          │    
│  66 - kpis = engine.get_kpi_indicators()                                                                                                                                                                                                       │    
│  67 - lt_metrics = engine.get_long_term_tracking_metrics(filtered_df)                                                                                                                                                                          │    
│  68 -                                                                                                                                                                                                                                          │    
│  69 - m1, m2, m3, m4 = st.columns(4)                                                                                                                                                                                                           │    
│  70 - with m1:                                                                                                                                                                                                                                 │    
│  71 -     st.metric("🌍 분석 대상 모객량", f"{int(kpis['총리뷰건수']):,}건", help="수집된 전체 리뷰 데이터의 건수입니다.")                                                                                                                     │    
│  72 - with m2:                                                                                                                                                                                                                                 │    
│  73 -     st.metric("⭐ 시장 평균 만족도", f"{kpis['전체평균평점']:.2f} / 5.0", help="전체 상품의 평균 고객 만족도입니다.")                                                                                                                    │    
│  74 - with m3:                                                                                                                                                                                                                                 │    
│  75 -     st.metric("🚨 실시간 고위험률", f"{lt_metrics['high_risk_ratio']:.1f}%", f"{lt_metrics['high_risk_count']}건", delta_color="inverse")                                                                                                │    
│  76 - with m4:                                                                                                                                                                                                                                 │    
│  77 -     st.metric("🛍️ 평균 쇼핑 강도", f"{kpis['평균쇼핑횟수']:.1f}회", help="상품당 포함된 평균 쇼핑센터 방문 횟수입니다.")                                                                                                                 │    
│  78 -                                                                                                                                                                                                                                          │    
│  79 - st.markdown("---")                                                                                                                                                                                                                       │    
│  80 -                                                                                                                                                                                                                                          │    
│  81 - # ---------------------------------------------------------                                                                                                                                                                              │    
│  82 - # [단계 1] 📈 글로벌 항공 및 타겟 노선 거시 분석                                                                                                                                                                                         │    
│  83 - # ---------------------------------------------------------                                                                                                                                                                              │    
│  84 - if "1." in selected_menu:                                                                                                                                                                                                                │    
│  85 -     st.header("📈 1. 글로벌 항공 및 타겟 노선 거시 분석 (Market Insight)")                                                                                                                                                               │    
│  86 -                                                                                                                                                                                                                                          │    
    with col2:
        monthly_perf = engine.get_monthly_aviation_performance()
        st.plotly_chart(px.area(monthly_perf, x="월", y="유임승객(명)", title="월별 항공 수요 변동 (시즈널리티 분석)"), use_container_width=True)

    # 1-2. 국가/도시별 누적 실적 및 항공사 점유율 (FSC vs LCC)
    st.subheader("📊 국가 및 도시별 누적 성과 및 브랜드 점유율")
    c1, c2, c3 = st.columns(3)
    with c1:
        country_data = engine.get_cumulative_performance_by_country().head(10)
        st.plotly_chart(px.bar(country_data, x="유임승객(명)", y="국가", orientation='h', title="국가별 누적 실적 (Top 10)"), use_container_width=True)
    with c2:
        city_cum_data = engine.get_cumulative_performance_by_city().head(10)
        st.plotly_chart(px.bar(city_cum_data, x="유임승객(명)", y="도시", orientation='h', title="도시별 누적 실적 (Top 10)"), use_container_width=True)